name: print dates

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: run job1
        run: echo $(date)

  job2:
    runs-on: windows-latest

    steps:
      - name: run job2
        run: echo $(date)

  job3:
    runs-on: macos-latest

    steps:
      - name: run job3
        run: echo $(date)

  job4:
    runs-on: ubuntu-latest

    steps:
      - name: run job4
        run: echo $(date)

    needs: [job1, job2, job3]

